// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: yamcs/protobuf/services/services.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// service states coming from guava (numbers have to correspond)
type ServiceState int32

const (
	// A service in this state is inactive. It does minimal work and
	// consumes minimal resources.
	ServiceState_NEW ServiceState = 0
	// A service in this state is transitioning to “RUNNING“.
	ServiceState_STARTING ServiceState = 1
	// A service in this state is operational.
	ServiceState_RUNNING ServiceState = 2
	// A service in this state is transitioning to “TERMINATED“.
	ServiceState_STOPPING ServiceState = 3
	// A service in this state has completed execution normally.
	// It does minimal work and consumes minimal resources.
	ServiceState_TERMINATED ServiceState = 4
	// A service in this state has encountered a problem and may
	// not be operational. It cannot be started nor stopped.
	ServiceState_FAILED ServiceState = 5
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "NEW",
		1: "STARTING",
		2: "RUNNING",
		3: "STOPPING",
		4: "TERMINATED",
		5: "FAILED",
	}
	ServiceState_value = map[string]int32{
		"NEW":        0,
		"STARTING":   1,
		"RUNNING":    2,
		"STOPPING":   3,
		"TERMINATED": 4,
		"FAILED":     5,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_yamcs_protobuf_services_services_proto_enumTypes[0].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_yamcs_protobuf_services_services_proto_enumTypes[0]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ServiceState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ServiceState(num)
	return nil
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_yamcs_protobuf_services_services_proto_rawDescGZIP(), []int{0}
}

type ServiceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// Service name
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Service state
	State *ServiceState `protobuf:"varint,3,opt,name=state,enum=yamcs.protobuf.services.ServiceState" json:"state,omitempty"`
	// Java class name
	ClassName *string `protobuf:"bytes,4,opt,name=className" json:"className,omitempty"`
	// Processor name (in case this is a processor service)
	Processor *string `protobuf:"bytes,5,opt,name=processor" json:"processor,omitempty"`
	// Short failure message when `state` is FAILED.
	FailureMessage *string `protobuf:"bytes,6,opt,name=failureMessage" json:"failureMessage,omitempty"`
	// Stacktrace when `state` is FAILED.
	FailureCause  *string `protobuf:"bytes,7,opt,name=failureCause" json:"failureCause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_yamcs_protobuf_services_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_services_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_services_services_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ServiceInfo) GetState() ServiceState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ServiceState_NEW
}

func (x *ServiceInfo) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *ServiceInfo) GetProcessor() string {
	if x != nil && x.Processor != nil {
		return *x.Processor
	}
	return ""
}

func (x *ServiceInfo) GetFailureMessage() string {
	if x != nil && x.FailureMessage != nil {
		return *x.FailureMessage
	}
	return ""
}

func (x *ServiceInfo) GetFailureCause() string {
	if x != nil && x.FailureCause != nil {
		return *x.FailureCause
	}
	return ""
}

var File_yamcs_protobuf_services_services_proto protoreflect.FileDescriptor

var file_yamcs_protobuf_services_services_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x22, 0x82, 0x02, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x3b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x25, 0x2e, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x43, 0x61, 0x75,
	0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x43, 0x61, 0x75, 0x73, 0x65, 0x2a, 0x5c, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54,
	0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x52, 0x4d,
	0x49, 0x4e, 0x41, 0x54, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x05, 0x42, 0x6d, 0x0a, 0x12, 0x6f, 0x72, 0x67, 0x2e, 0x79, 0x61, 0x6d, 0x63,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x0d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x46, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x6f, 0x70, 0x73, 0x2d, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x2d, 0x79, 0x61, 0x6d, 0x63,
	0x73, 0x2d, 0x6a, 0x61, 0x6f, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x61, 0x6d, 0x63,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73,
})

var (
	file_yamcs_protobuf_services_services_proto_rawDescOnce sync.Once
	file_yamcs_protobuf_services_services_proto_rawDescData []byte
)

func file_yamcs_protobuf_services_services_proto_rawDescGZIP() []byte {
	file_yamcs_protobuf_services_services_proto_rawDescOnce.Do(func() {
		file_yamcs_protobuf_services_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yamcs_protobuf_services_services_proto_rawDesc), len(file_yamcs_protobuf_services_services_proto_rawDesc)))
	})
	return file_yamcs_protobuf_services_services_proto_rawDescData
}

var file_yamcs_protobuf_services_services_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yamcs_protobuf_services_services_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yamcs_protobuf_services_services_proto_goTypes = []any{
	(ServiceState)(0),   // 0: yamcs.protobuf.services.ServiceState
	(*ServiceInfo)(nil), // 1: yamcs.protobuf.services.ServiceInfo
}
var file_yamcs_protobuf_services_services_proto_depIdxs = []int32{
	0, // 0: yamcs.protobuf.services.ServiceInfo.state:type_name -> yamcs.protobuf.services.ServiceState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yamcs_protobuf_services_services_proto_init() }
func file_yamcs_protobuf_services_services_proto_init() {
	if File_yamcs_protobuf_services_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yamcs_protobuf_services_services_proto_rawDesc), len(file_yamcs_protobuf_services_services_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yamcs_protobuf_services_services_proto_goTypes,
		DependencyIndexes: file_yamcs_protobuf_services_services_proto_depIdxs,
		EnumInfos:         file_yamcs_protobuf_services_services_proto_enumTypes,
		MessageInfos:      file_yamcs_protobuf_services_services_proto_msgTypes,
	}.Build()
	File_yamcs_protobuf_services_services_proto = out.File
	file_yamcs_protobuf_services_services_proto_goTypes = nil
	file_yamcs_protobuf_services_services_proto_depIdxs = nil
}
