[supervisord]
nodaemon=true
user=root

[program:grafana]
user=root
directory=/var/lib/grafana
command=bash -c 'while [ ! -f /root/jaops-yamcs-app/dist/gpx_grafana_yamcs_jaops* ]; do sleep 1; done; /run.sh'
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
killasgroup=true
stopasgroup=true
autostart=true

[program:delve]
user=root
command=/bin/bash -c 'while true; do pid=$(pidof gpx_grafana_yamcs_jaops_linux_amd64 | tr " " "\n" | sort -nr | head -n 1); if [ -z "$pid" ]; then sleep 0.5; continue; fi; if ! kill -0 "$pid" 2>/dev/null; then sleep 0.2; continue; fi; /root/go/bin/dlv attach --api-version=2 --headless --continue --accept-multiclient --listen=:2345 "$pid"; echo "dlv exited, retrying attach"; sleep 0.5; done'
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
killasgroup=true
stopasgroup=true
autostart=true
autorestart=true

[program:build-watcher]
user=root
command=/bin/bash -c 'while inotifywait -e modify,create,delete -r /var/lib/grafana/plugins/jaops-yamcs-app; do echo "Change detected, restarting delve...";supervisorctl restart delve; done'
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
killasgroup=true
stopasgroup=true
autostart=true

[program:mage-watcher]
user=root
environment=PATH="/usr/local/go/bin:/root/go/bin:%(ENV_PATH)s"
directory=/root/jaops-yamcs-app
command=/bin/bash -c 'git config --global --add safe.directory /root/jaops-yamcs-app && mage -v watch'
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
killasgroup=true
stopasgroup=true
autostart=true

