// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: yamcs/protobuf/activities/activities.proto

package activities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityStatus int32

const (
	// An activity is runing
	ActivityStatus_RUNNING ActivityStatus = 1
	// The activity was cancelled. It may or may not still be running
	// (verify stop time).
	ActivityStatus_CANCELLED ActivityStatus = 2
	// The activity completed successfully
	ActivityStatus_SUCCESSFUL ActivityStatus = 3
	// An error occurred while running this activity
	ActivityStatus_FAILED ActivityStatus = 4
)

// Enum value maps for ActivityStatus.
var (
	ActivityStatus_name = map[int32]string{
		1: "RUNNING",
		2: "CANCELLED",
		3: "SUCCESSFUL",
		4: "FAILED",
	}
	ActivityStatus_value = map[string]int32{
		"RUNNING":    1,
		"CANCELLED":  2,
		"SUCCESSFUL": 3,
		"FAILED":     4,
	}
)

func (x ActivityStatus) Enum() *ActivityStatus {
	p := new(ActivityStatus)
	*p = x
	return p
}

func (x ActivityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yamcs_protobuf_activities_activities_proto_enumTypes[0].Descriptor()
}

func (ActivityStatus) Type() protoreflect.EnumType {
	return &file_yamcs_protobuf_activities_activities_proto_enumTypes[0]
}

func (x ActivityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActivityStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActivityStatus(num)
	return nil
}

// Deprecated: Use ActivityStatus.Descriptor instead.
func (ActivityStatus) EnumDescriptor() ([]byte, []int) {
	return file_yamcs_protobuf_activities_activities_proto_rawDescGZIP(), []int{0}
}

type ActivityLogLevel int32

const (
	// Info level
	ActivityLogLevel_INFO ActivityLogLevel = 1
	// Warning level
	ActivityLogLevel_WARNING ActivityLogLevel = 2
	// Error level
	ActivityLogLevel_ERROR ActivityLogLevel = 3
)

// Enum value maps for ActivityLogLevel.
var (
	ActivityLogLevel_name = map[int32]string{
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	ActivityLogLevel_value = map[string]int32{
		"INFO":    1,
		"WARNING": 2,
		"ERROR":   3,
	}
)

func (x ActivityLogLevel) Enum() *ActivityLogLevel {
	p := new(ActivityLogLevel)
	*p = x
	return p
}

func (x ActivityLogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityLogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_yamcs_protobuf_activities_activities_proto_enumTypes[1].Descriptor()
}

func (ActivityLogLevel) Type() protoreflect.EnumType {
	return &file_yamcs_protobuf_activities_activities_proto_enumTypes[1]
}

func (x ActivityLogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ActivityLogLevel) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ActivityLogLevel(num)
	return nil
}

// Deprecated: Use ActivityLogLevel.Descriptor instead.
func (ActivityLogLevel) EnumDescriptor() ([]byte, []int) {
	return file_yamcs_protobuf_activities_activities_proto_rawDescGZIP(), []int{1}
}

type ActivityDefinitionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Activity type.
	// Common types: MANUAL, SCRIPT, COMMAND, COMMAND_STACK
	Type *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Activity arguments. The expected arguments
	// are different for each activity type
	Args *structpb.Struct `protobuf:"bytes,2,opt,name=args" json:"args,omitempty"`
	// Optional comment
	Comment       *string `protobuf:"bytes,3,opt,name=comment" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDefinitionInfo) Reset() {
	*x = ActivityDefinitionInfo{}
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDefinitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDefinitionInfo) ProtoMessage() {}

func (x *ActivityDefinitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDefinitionInfo.ProtoReflect.Descriptor instead.
func (*ActivityDefinitionInfo) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_activities_activities_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityDefinitionInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ActivityDefinitionInfo) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ActivityDefinitionInfo) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type ActivityInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Activity identifier
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Start time of the activity
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	// Differentiator in case of multiple activities
	// with the same start time
	Seq *uint32 `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	// Activity status
	Status *ActivityStatus `protobuf:"varint,4,opt,name=status,enum=yamcs.protobuf.activities.ActivityStatus" json:"status,omitempty"`
	// User who started the run
	StartedBy *string `protobuf:"bytes,5,opt,name=startedBy" json:"startedBy,omitempty"`
	// Activity type
	Type *string `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
	// Activity arguments
	Args *structpb.Struct `protobuf:"bytes,7,opt,name=args" json:"args,omitempty"`
	// Activity detail (short descriptive)
	Detail *string `protobuf:"bytes,8,opt,name=detail" json:"detail,omitempty"`
	// Stop time of the activity run
	Stop *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=stop" json:"stop,omitempty"`
	// User who stopped the run. Only set if the activity
	// was manually stopped
	StoppedBy *string `protobuf:"bytes,10,opt,name=stoppedBy" json:"stoppedBy,omitempty"`
	// If set, the activity is stopped, but failed
	FailureReason *string `protobuf:"bytes,11,opt,name=failureReason" json:"failureReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_activities_activities_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityInfo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ActivityInfo) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ActivityInfo) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *ActivityInfo) GetStatus() ActivityStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ActivityStatus_RUNNING
}

func (x *ActivityInfo) GetStartedBy() string {
	if x != nil && x.StartedBy != nil {
		return *x.StartedBy
	}
	return ""
}

func (x *ActivityInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ActivityInfo) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ActivityInfo) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *ActivityInfo) GetStop() *timestamppb.Timestamp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ActivityInfo) GetStoppedBy() string {
	if x != nil && x.StoppedBy != nil {
		return *x.StoppedBy
	}
	return ""
}

func (x *ActivityInfo) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

type ExecutorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Executor type name
	Type *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Display name
	DisplayName *string `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	// Executor description
	Description *string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// Name of an icon in the Material Icons font.
	Icon          *string `protobuf:"bytes,4,opt,name=icon" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorInfo) Reset() {
	*x = ExecutorInfo{}
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorInfo) ProtoMessage() {}

func (x *ExecutorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorInfo.ProtoReflect.Descriptor instead.
func (*ExecutorInfo) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_activities_activities_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutorInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ExecutorInfo) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *ExecutorInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ExecutorInfo) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

type ActivityLogInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log time
	Time *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	// Source of this log message. One of:
	//
	// - SERVICE: the log is generated by the activity service
	// - ACTIVITY: the log is generated by the activity itself
	Source *string `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	// Log level
	Level *ActivityLogLevel `protobuf:"varint,3,opt,name=level,enum=yamcs.protobuf.activities.ActivityLogLevel" json:"level,omitempty"`
	// Log message
	Message       *string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityLogInfo) Reset() {
	*x = ActivityLogInfo{}
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityLogInfo) ProtoMessage() {}

func (x *ActivityLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_activities_activities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityLogInfo.ProtoReflect.Descriptor instead.
func (*ActivityLogInfo) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_activities_activities_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityLogInfo) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ActivityLogInfo) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ActivityLogInfo) GetLevel() ActivityLogLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return ActivityLogLevel_INFO
}

func (x *ActivityLogInfo) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_yamcs_protobuf_activities_activities_proto protoreflect.FileDescriptor

var file_yamcs_protobuf_activities_activities_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x79, 0x61,
	0x6d, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x90, 0x03, 0x0a, 0x0c,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71,
	0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x29, 0x2e, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x73, 0x74,
	0x6f, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x6f, 0x70, 0x70, 0x65, 0x64, 0x42, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x42, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x7a,
	0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0xb6, 0x01, 0x0a, 0x0f, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0x48, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x46, 0x55, 0x4c, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x34, 0x0a,
	0x10, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x57,
	0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x03, 0x42, 0x7c, 0x0a, 0x1d, 0x6f, 0x72, 0x67, 0x2e, 0x79, 0x61, 0x6d, 0x63, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x42, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x6f, 0x70, 0x73, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f,
	0x67, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x2d, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2d, 0x6a, 0x61,
	0x6f, 0x70, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x61, 0x6d, 0x63, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65,
	0x73,
})

var (
	file_yamcs_protobuf_activities_activities_proto_rawDescOnce sync.Once
	file_yamcs_protobuf_activities_activities_proto_rawDescData []byte
)

func file_yamcs_protobuf_activities_activities_proto_rawDescGZIP() []byte {
	file_yamcs_protobuf_activities_activities_proto_rawDescOnce.Do(func() {
		file_yamcs_protobuf_activities_activities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yamcs_protobuf_activities_activities_proto_rawDesc), len(file_yamcs_protobuf_activities_activities_proto_rawDesc)))
	})
	return file_yamcs_protobuf_activities_activities_proto_rawDescData
}

var file_yamcs_protobuf_activities_activities_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_yamcs_protobuf_activities_activities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yamcs_protobuf_activities_activities_proto_goTypes = []any{
	(ActivityStatus)(0),            // 0: yamcs.protobuf.activities.ActivityStatus
	(ActivityLogLevel)(0),          // 1: yamcs.protobuf.activities.ActivityLogLevel
	(*ActivityDefinitionInfo)(nil), // 2: yamcs.protobuf.activities.ActivityDefinitionInfo
	(*ActivityInfo)(nil),           // 3: yamcs.protobuf.activities.ActivityInfo
	(*ExecutorInfo)(nil),           // 4: yamcs.protobuf.activities.ExecutorInfo
	(*ActivityLogInfo)(nil),        // 5: yamcs.protobuf.activities.ActivityLogInfo
	(*structpb.Struct)(nil),        // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_yamcs_protobuf_activities_activities_proto_depIdxs = []int32{
	6, // 0: yamcs.protobuf.activities.ActivityDefinitionInfo.args:type_name -> google.protobuf.Struct
	7, // 1: yamcs.protobuf.activities.ActivityInfo.start:type_name -> google.protobuf.Timestamp
	0, // 2: yamcs.protobuf.activities.ActivityInfo.status:type_name -> yamcs.protobuf.activities.ActivityStatus
	6, // 3: yamcs.protobuf.activities.ActivityInfo.args:type_name -> google.protobuf.Struct
	7, // 4: yamcs.protobuf.activities.ActivityInfo.stop:type_name -> google.protobuf.Timestamp
	7, // 5: yamcs.protobuf.activities.ActivityLogInfo.time:type_name -> google.protobuf.Timestamp
	1, // 6: yamcs.protobuf.activities.ActivityLogInfo.level:type_name -> yamcs.protobuf.activities.ActivityLogLevel
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_yamcs_protobuf_activities_activities_proto_init() }
func file_yamcs_protobuf_activities_activities_proto_init() {
	if File_yamcs_protobuf_activities_activities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yamcs_protobuf_activities_activities_proto_rawDesc), len(file_yamcs_protobuf_activities_activities_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yamcs_protobuf_activities_activities_proto_goTypes,
		DependencyIndexes: file_yamcs_protobuf_activities_activities_proto_depIdxs,
		EnumInfos:         file_yamcs_protobuf_activities_activities_proto_enumTypes,
		MessageInfos:      file_yamcs_protobuf_activities_activities_proto_msgTypes,
	}.Build()
	File_yamcs_protobuf_activities_activities_proto = out.File
	file_yamcs_protobuf_activities_activities_proto_goTypes = nil
	file_yamcs_protobuf_activities_activities_proto_depIdxs = nil
}
