name: Bundle Stats

on:
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    actions: read

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    compare:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: grafana/plugin-actions/bundle-size@main
