name: Bundle Stats

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: write
    issues: write
    actions: read

jobs:
    compare:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: grafana/plugin-actions/bundle-size@main
